BotInfo:
  Token: "YOUR TOKEN HERE"
  ServerID: "YOUR DISCORD SERVER ID HERE"
  PterodactylUrl: "YOUR URL HERE"
  AdminApiKey: "YOUR PTERODACTYL ADMIN CLIENT KEY HERE"
  Status: "ONLINE" # DND, ONLINE, IDLE, INVISIBLE
  EnableActivity: true
  Activity: "PLAYING" # PLAYING LISTENING and WATCHING
  ActivityName: "Pterodactyl !"
Messages:
  Commands:
    Link:
      Description: "Connect your pterodactyl account using this command !"
      OptionDescription: "Enter your pterodactyl api key here !"
      LinkSuccess: "You successfully linked your discord account with %pteroName pterodactyl account"
      LinkExist: "Sorry, but you already have pterodactyl account linked !"
      LinkWrongKey: "Sorry, that api key is wrong !"
    NodeInfo:
      Description: "Shows specific node info or all nodes online status (depends on options)"
      OptionDescription: "ID of node you want to show info of"
      OptionUpdateDescription: "If true, bot will edit this message every 5 minutes with new info, be careful because of rate-limit"
      NodeNotFound: "Sorry, requested node is not found"
      NotAdmin: "Sorry, your linked pterodactyl key doesn't seems to have admin permissions !"
      OnlineEmoji: "🟢"
      OfflineEmoji: "🔴"
    Register:
      Description: "Registers new account to pterodactyl panel !"
      InvalidEmail: "Sorry, this doesn't look like valid email address :("
      PasswordRequired: true # set this to false only if your panel is able to send mails (this will send random password to user)
      Success: "You successfully created account named %pteroName"
      FieldTaken: "Sorry, but provided %takenField is already taken"
      Modal:
        Name: "PteroBot registration"
        EmailPlaceholder: "Please enter your email here"
        UsernamePlaceholder: "Enter your username here"
        PasswordPlaceholder: "Enter your password, if not specified panel will generate one"
        FirstNamePlaceholder: "Enter your first name here"
        LastNamePlaceholder: "Enter your last name here"
    Servers:
      Description: "Select server you want to interact with"
      NotLinked: "Sorry, your discord isn't linked with any pterodactyl account, link one using /link"
      NotFound: "Sorry, but your account isn't found anymore (deleted apy key) ?"
      MenuPlaceholder: "Please select server you would like"
  Embeds:
    UnexpectedError: "Unexpected error happened, check console for more details !"