name: PteroBot create release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release PteroBot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 8
          distribution: temurin

      - name: Change version
        id: version
        env:
          REF: ${{ github.ref }}
        run: |
          sed -i "s/canary/${REF:11}/g" pom.xml
          echo "name=PteroBot-${REF:11}.jar" >> $GITHUB_OUTPUT

      - name: Build PteroBot
        run: mvn -B package --file pom.xml

      - name: Generate checksum
        id: checksum
        run: |
          cd target/
          CHECKSUM=`sha256sum ${{ steps.version.outputs.name }}`
          echo $CHECKSUM > ../checksum.txt
          echo "checksum=### SHA256 checksum<br /> \`\`\`$CHECKSUM\`\`\`" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            target/${{ steps.version.outputs.name }}
            checksum.txt
          draft: true
          generate_release_notes: true
          append_body: true
          body: ${{ steps.checksum.outputs.checksum }}