name: PteroBot create release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release PteroBot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Change version
        env:
          REF: ${{github.ref}}
        run: sed -i 's/canary/${REF:11}/g' pom.xml

      - name: Build changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: echo ${{steps.changelog.outputs.changelog}}

      - name: Build PteroBot
        run: mvn -B package --file pom.xml